### ISSUE TITLE
[CSS] Contribute `.text-large` and `.text-huge` classes from downstream projects

### ISSUE THREAD

**Issue by claudiopro** [emeraldion/aoi#1]
# Summary
Add Sass rules to generate CSS like the following:

```css 
.form .form-row .form-field input[type='date'].text-large,
.form .form-row .form-field input[type='datetime-local'].text-large,
.form .form-row .form-field input[type='number'].text-large,
.form .form-row .form-field input[type='search'].text-large,
.form .form-row .form-field input[type='text'].text-large,
.form .form-row .form-field input[type='password'].text-large,
.form .form-row .form-field select.select-large,
.form .form-row .form-field input[type='text'].text-large {
  font-size: 24px;
  height: 48px;
}

.form .form-row .form-field input[type='date'].text-huge,
.form .form-row .form-field input[type='datetime-local'].text-huge,
.form .form-row .form-field input[type='number'].text-huge,
.form .form-row .form-field input[type='search'].text-huge,
.form .form-row .form-field input[type='text'].text-huge,
.form .form-row .form-field input[type='password'].text-huge,
.form .form-row .form-field select.select-huge,
.form .form-row .form-field input[type='text'].text-huge {
  font-size: 36px;
  height: 72px;
}
```
